const countries = [
    {'code': 'US', 'name': 'United States', 'flag': '🇺🇸'},
    {'code': 'CA', 'name': 'Canada', 'flag': '🇨🇦'},
    {'code': 'AF', 'name': 'Afghanistan', 'flag': '🇦🇫'},
    {'code': 'AL', 'name': 'Albania', 'flag': '🇦🇱'},
    {'code': 'DZ', 'name': 'Algeria', 'flag': '🇩🇿'},
    {'code': 'AS', 'name': 'American Samoa', 'flag': '🇦🇸'},
    {'code': 'AD', 'name': 'Andorra', 'flag': '🇦🇩'},
    {'code': 'AO', 'name': 'Angola', 'flag': '🇦🇴'},
    {'code': 'AI', 'name': 'Anguilla', 'flag': '🇦🇮'},
    {'code': 'AQ', 'name': 'Antarctica', 'flag': '🇦🇶'},
    {'code': 'AG', 'name': 'Antigua and/or Barbuda', 'flag': '🇦🇬'},
    {'code': 'AR', 'name': 'Argentina', 'flag': '🇦🇷'},
    {'code': 'AM', 'name': 'Armenia', 'flag': '🇦🇲'},
    {'code': 'AW', 'name': 'Aruba', 'flag': '🇦🇼'},
    {'code': 'AU', 'name': 'Australia', 'flag': '🇦🇺'},
    {'code': 'AT', 'name': 'Austria', 'flag': '🇦🇹'},
    {'code': 'AZ', 'name': 'Azerbaijan', 'flag': '🇦🇿'},
    {'code': 'BS', 'name': 'Bahamas', 'flag': '🇧🇸'},
    {'code': 'BH', 'name': 'Bahrain', 'flag': '🇧🇭'},
    {'code': 'BD', 'name': 'Bangladesh', 'flag': '🇧🇩'},
    {'code': 'BB', 'name': 'Barbados', 'flag': '🇧🇧'},
    {'code': 'BY', 'name': 'Belarus', 'flag': '🇧🇾'},
    {'code': 'BE', 'name': 'Belgium', 'flag': '🇧🇪'},
    {'code': 'BZ', 'name': 'Belize', 'flag': '🇧🇿'},
    {'code': 'BJ', 'name': 'Benin', 'flag': '🇧🇯'},
    {'code': 'BM', 'name': 'Bermuda', 'flag': '🇧🇲'},
    {'code': 'BT', 'name': 'Bhutan', 'flag': '🇧🇹'},
    {'code': 'BO', 'name': 'Bolivia', 'flag': '🇧🇴'},
    {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'flag': '🇧🇦'},
    {'code': 'BW', 'name': 'Botswana', 'flag': '🇧🇼'},
    {'code': 'BV', 'name': 'Bouvet Island', 'flag': '🇧🇻'},
    {'code': 'BR', 'name': 'Brazil', 'flag': '🇧🇷'},
    {'code': 'IO', 'name': 'British lndian Ocean Territory', 'flag': '🇮🇴'},
    {'code': 'BN', 'name': 'Brunei Darussalam', 'flag': '🇧🇳'},
    {'code': 'BG', 'name': 'Bulgaria', 'flag': '🇧🇬'},
    {'code': 'BF', 'name': 'Burkina Faso', 'flag': '🇧🇫'},
    {'code': 'BI', 'name': 'Burundi', 'flag': '🇧🇮'},
    {'code': 'KH', 'name': 'Cambodia', 'flag': '🇰🇭'},
    {'code': 'CM', 'name': 'Cameroon', 'flag': '🇨🇲'},
    {'code': 'CV', 'name': 'Cape Verde', 'flag': '🇨🇻'},
    {'code': 'KY', 'name': 'Cayman Islands', 'flag': '🇰🇾'},
    {'code': 'CF', 'name': 'Central African Republic', 'flag': '🇨🇫'},
    {'code': 'TD', 'name': 'Chad', 'flag': '🇹🇩'},
    {'code': 'CL', 'name': 'Chile', 'flag': '🇨🇱'},
    {'code': 'CN', 'name': 'China', 'flag': '🇨🇳'},
    {'code': 'CX', 'name': 'Christmas Island', 'flag': '🇨🇽'},
    {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'flag': '🇨🇨'},
    {'code': 'CO', 'name': 'Colombia', 'flag': '🇨🇴'},
    {'code': 'KM', 'name': 'Comoros', 'flag': '🇰🇲'},
    {'code': 'CG', 'name': 'Congo', 'flag': '🇨🇬'},
    {'code': 'CK', 'name': 'Cook Islands', 'flag': '🇨🇰'},
    {'code': 'CR', 'name': 'Costa Rica', 'flag': '🇨🇷'},
    {'code': 'HR', 'name': 'Croatia (Hrvatska)', 'flag': '🇭🇷'},
    {'code': 'CU', 'name': 'Cuba', 'flag': '🇨🇺'},
    {'code': 'CY', 'name': 'Cyprus', 'flag': '🇨🇾'},
    {'code': 'CZ', 'name': 'Czech Republic', 'flag': '🇨🇿'},
    {'code': 'CD', 'name': 'Democratic Republic of Congo', 'flag': '🇨🇩'},
    {'code': 'DK', 'name': 'Denmark', 'flag': '🇩🇰'},
    {'code': 'DJ', 'name': 'Djibouti', 'flag': '🇩🇯'},
    {'code': 'DM', 'name': 'Dominica', 'flag': '🇩🇲'},
    {'code': 'DO', 'name': 'Dominican Republic', 'flag': '🇩🇴'},
    {'code': 'TP', 'name': 'East Timor', 'flag': '🇹🇱'},
    {'code': 'EC', 'name': 'Ecudaor', 'flag': '🇪🇨'},
    {'code': 'EG', 'name': 'Egypt', 'flag': '🇪🇬'},
    {'code': 'SV', 'name': 'El Salvador', 'flag': '🇸🇻'},
    {'code': 'GQ', 'name': 'Equatorial Guinea', 'flag': '🇬🇶'},
    {'code': 'ER', 'name': 'Eritrea', 'flag': '🇪🇷'},
    {'code': 'EE', 'name': 'Estonia', 'flag': '🇪🇪'},
    {'code': 'ET', 'name': 'Ethiopia', 'flag': '🇪🇹'},
    {'code': 'FK', 'name': 'Falkland Islands (Malvinas)', 'flag': '🇫🇰'},
    {'code': 'FO', 'name': 'Faroe Islands', 'flag': '🇫🇴'},
    {'code': 'FJ', 'name': 'Fiji', 'flag': '🇫🇯'},
    {'code': 'FI', 'name': 'Finland', 'flag': '🇫🇮'},
    {'code': 'FR', 'name': 'France', 'flag': '🇫🇷'},
    {'code': 'FX', 'name': 'France, Metropolitan', 'flag': '🇫🇷'},
    {'code': 'GF', 'name': 'French Guiana', 'flag': '🇬🇫'},
    {'code': 'PF', 'name': 'French Polynesia', 'flag': '🇵🇫'},
    {'code': 'TF', 'name': 'French Southern Territories', 'flag': '🇹🇫'},
    {'code': 'GA', 'name': 'Gabon', 'flag': '🇬🇦'},
    {'code': 'GM', 'name': 'Gambia', 'flag': '🇬🇲'},
    {'code': 'GE', 'name': 'Georgia', 'flag': '🇬🇪'},
    {'code': 'DE', 'name': 'Germany', 'flag': '🇩🇪'},
    {'code': 'GH', 'name': 'Ghana', 'flag': '🇬🇭'},
    {'code': 'GI', 'name': 'Gibraltar', 'flag': '🇬🇮'},
    {'code': 'GR', 'name': 'Greece', 'flag': '🇬🇷'},
    {'code': 'GL', 'name': 'Greenland', 'flag': '🇬🇱'},
    {'code': 'GD', 'name': 'Grenada', 'flag': '🇬🇩'},
    {'code': 'GP', 'name': 'Guadeloupe', 'flag': '🇬🇵'},
    {'code': 'GU', 'name': 'Guam', 'flag': '🇬🇺'},
    {'code': 'GT', 'name': 'Guatemala', 'flag': '🇬🇹'},
    {'code': 'GN', 'name': 'Guinea', 'flag': '🇬🇳'},
    {'code': 'GW', 'name': 'Guinea-Bissau', 'flag': '🇬🇼'},
    {'code': 'GY', 'name': 'Guyana', 'flag': '🇬🇾'},
    {'code': 'HT', 'name': 'Haiti', 'flag': '🇭🇹'},
    {'code': 'HM', 'name': 'Heard and Mc Donald Islands', 'flag': '🇭🇲'},
    {'code': 'HN', 'name': 'Honduras', 'flag': '🇭🇳'},
    {'code': 'HK', 'name': 'Hong Kong', 'flag': '🇭🇰'},
    {'code': 'HU', 'name': 'Hungary', 'flag': '🇭🇺'},
    {'code': 'IS', 'name': 'Iceland', 'flag': '🇮🇸'},
    {'code': 'IN', 'name': 'India', 'flag': '🇮🇳'},
    {'code': 'ID', 'name': 'Indonesia', 'flag': '🇮🇩'},
    {'code': 'IR', 'name': 'Iran (Islamic Republic of)', 'flag': '🇮🇷'},
    {'code': 'IQ', 'name': 'Iraq', 'flag': '🇮🇶'},
    {'code': 'IE', 'name': 'Ireland', 'flag': '🇮🇪'},
    {'code': 'IL', 'name': 'Israel', 'flag': '🇮🇱'},
    {'code': 'IT', 'name': 'Italy', 'flag': '🇮🇹'},
    {'code': 'CI', 'name': 'Ivory Coast', 'flag': '🇨🇮'},
    {'code': 'JM', 'name': 'Jamaica', 'flag': '🇯🇲'},
    {'code': 'JP', 'name': 'Japan', 'flag': '🇯🇵'},
    {'code': 'JO', 'name': 'Jordan', 'flag': '🇯🇴'},
    {'code': 'KZ', 'name': 'Kazakhstan', 'flag': '🇰🇿'},
    {'code': 'KE', 'name': 'Kenya', 'flag': '🇰🇪'},
    {'code': 'KI', 'name': 'Kiribati', 'flag': '🇰🇮'},
    {'code': 'KP', 'name': 'Korea, Democratic People\'s Republic of', 'flag': '🇰🇵'},
    {'code': 'KR', 'name': 'Korea, Republic of', 'flag': '🇰🇷'},
    {'code': 'KW', 'name': 'Kuwait', 'flag': '🇰🇼'},
    {'code': 'KG', 'name': 'Kyrgyzstan', 'flag': '🇰🇬'},
    {'code': 'LA', 'name': 'Lao People\'s Democratic Republic', 'flag': '🇱🇦'},
    {'code': 'LV', 'name': 'Latvia', 'flag': '🇱🇻'},
    {'code': 'LB', 'name': 'Lebanon', 'flag': '🇱🇧'},
    {'code': 'LS', 'name': 'Lesotho', 'flag': '🇱🇸'},
    {'code': 'LR', 'name': 'Liberia', 'flag': '🇱🇷'},
    {'code': 'LY', 'name': 'Libyan Arab Jamahiriya', 'flag': '🇱🇾'},
    {'code': 'LI', 'name': 'Liechtenstein', 'flag': '🇱🇮'},
    {'code': 'LT', 'name': 'Lithuania', 'flag': '🇱🇹'},
    {'code': 'LU', 'name': 'Luxembourg', 'flag': '🇱🇺'},
    {'code': 'MO', 'name': 'Macau', 'flag': '🇲🇴'},
    {'code': 'MK', 'name': 'Macedonia', 'flag': '🇲🇰'},
    {'code': 'MG', 'name': 'Madagascar', 'flag': '🇲🇬'},
    {'code': 'MW', 'name': 'Malawi', 'flag': '🇲🇼'},
    {'code': 'MY', 'name': 'Malaysia', 'flag': '🇲🇾'},
    {'code': 'MV', 'name': 'Maldives', 'flag': '🇲🇻'},
    {'code': 'ML', 'name': 'Mali', 'flag': '🇲🇱'},
    {'code': 'MT', 'name': 'Malta', 'flag': '🇲🇹'},
    {'code': 'MH', 'name': 'Marshall Islands', 'flag': '🇲🇭'},
    {'code': 'MQ', 'name': 'Martinique', 'flag': '🇲🇶'},
    {'code': 'MR', 'name': 'Mauritania', 'flag': '🇲🇷'},
    {'code': 'MU', 'name': 'Mauritius', 'flag': '🇲🇺'},
    {'code': 'TY', 'name': 'Mayotte', 'flag': '🇾🇹'},
    {'code': 'MX', 'name': 'Mexico', 'flag': '🇲🇽'},
    {'code': 'FM', 'name': 'Micronesia, Federated States of', 'flag': '🇫🇲'},
    {'code': 'MD', 'name': 'Moldova, Republic of', 'flag': '🇲🇩'},
    {'code': 'MC', 'name': 'Monaco', 'flag': '🇲🇨'},
    {'code': 'MN', 'name': 'Mongolia', 'flag': '🇲🇳'},
    {'code': 'MS', 'name': 'Montserrat', 'flag': '🇲🇸'},
    {'code': 'MA', 'name': 'Morocco', 'flag': '🇲🇦'},
    {'code': 'MZ', 'name': 'Mozambique', 'flag': '🇲🇿'},
    {'code': 'MM', 'name': 'Myanmar', 'flag': '🇲🇲'},
    {'code': 'NA', 'name': 'Namibia', 'flag': '🇳🇦'},
    {'code': 'NR', 'name': 'Nauru', 'flag': '🇳🇷'},
    {'code': 'NP', 'name': 'Nepal', 'flag': '🇳🇵'},
    {'code': 'NL', 'name': 'Netherlands', 'flag': '🇳🇱'},
    {'code': 'AN', 'name': 'Netherlands Antilles', 'flag': '🇳🇱'},
    {'code': 'NC', 'name': 'New Caledonia', 'flag': '🇳🇨'},
    {'code': 'NZ', 'name': 'New Zealand', 'flag': '🇳🇿'},
    {'code': 'NI', 'name': 'Nicaragua', 'flag': '🇳🇮'},
    {'code': 'NE', 'name': 'Niger', 'flag': '🇳🇪'},
    {'code': 'NG', 'name': 'Nigeria', 'flag': '🇳🇬'},
    {'code': 'NU', 'name': 'Niue', 'flag': '🇳🇺'},
    {'code': 'NF', 'name': 'Norfork Island', 'flag': '🇳🇫'},
    {'code': 'MP', 'name': 'Northern Mariana Islands', 'flag': '🇲🇵'},
    {'code': 'NO', 'name': 'Norway', 'flag': '🇳🇴'},
    {'code': 'OM', 'name': 'Oman', 'flag': '🇴🇲'},
    {'code': 'PK', 'name': 'Pakistan', 'flag': '🇵🇰'},
    {'code': 'PW', 'name': 'Palau', 'flag': '🇵🇼'},
    {'code': 'PA', 'name': 'Panama', 'flag': '🇵🇦'},
    {'code': 'PG', 'name': 'Papua New Guinea', 'flag': '🇵🇬'},
    {'code': 'PY', 'name': 'Paraguay', 'flag': '🇵🇾'},
    {'code': 'PE', 'name': 'Peru', 'flag': '🇵🇪'},
    {'code': 'PH', 'name': 'Philippines', 'flag': '🇵🇭'},
    {'code': 'PN', 'name': 'Pitcairn', 'flag': '🇵🇳'},
    {'code': 'PL', 'name': 'Poland', 'flag': '🇵🇱'},
    {'code': 'PT', 'name': 'Portugal', 'flag': '🇵🇹'},
    {'code': 'PR', 'name': 'Puerto Rico', 'flag': '🇵🇷'},
    {'code': 'QA', 'name': 'Qatar', 'flag': '🇶🇦'},
    {'code': 'SS', 'name': 'Republic of South Sudan', 'flag': '🇸🇸'},
    {'code': 'RE', 'name': 'Reunion', 'flag': '🇷🇪'},
    {'code': 'RO', 'name': 'Romania', 'flag': '🇷🇴'},
    {'code': 'RU', 'name': 'Russian Federation', 'flag': '🇷🇺'},
    {'code': 'RW', 'name': 'Rwanda', 'flag': '🇷🇼'},
    {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'flag': '🇰🇳'},
    {'code': 'LC', 'name': 'Saint Lucia', 'flag': '🇱🇨'},
    {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'flag': '🇻🇨'},
    {'code': 'WS', 'name': 'Samoa', 'flag': '🇼🇸'},
    {'code': 'SM', 'name': 'San Marino', 'flag': '🇸🇲'},
    {'code': 'ST', 'name': 'Sao Tome and Principe', 'flag': '🇸🇹'},
    {'code': 'SA', 'name': 'Saudi Arabia', 'flag': '🇸🇦'},
    {'code': 'SN', 'name': 'Senegal', 'flag': '🇸🇳'},
    {'code': 'RS', 'name': 'Serbia', 'flag': '🇷🇸'},
    {'code': 'SC', 'name': 'Seychelles', 'flag': '🇸🇨'},
    {'code': 'SL', 'name': 'Sierra Leone', 'flag': '🇸🇱'},
    {'code': 'SG', 'name': 'Singapore', 'flag': '🇸🇬'},
    {'code': 'SK', 'name': 'Slovakia', 'flag': '🇸🇰'},
    {'code': 'SI', 'name': 'Slovenia', 'flag': '🇸🇮'},
    {'code': 'SB', 'name': 'Solomon Islands', 'flag': '🇸🇧'},
    {'code': 'SO', 'name': 'Somalia', 'flag': '🇸🇴'},
    {'code': 'ZA', 'name': 'South Africa', 'flag': '🇿🇦'},
    {'code': 'GS', 'name': 'South Georgia South Sandwich Islands', 'flag': '🇬🇸'},
    {'code': 'ES', 'name': 'Spain', 'flag': '🇪🇸'},
    {'code': 'LK', 'name': 'Sri Lanka', 'flag': '🇱🇰'},
    {'code': 'SH', 'name': 'St. Helena', 'flag': '🇸🇭'},
    {'code': 'PM', 'name': 'St. Pierre and Miquelon', 'flag': '🇵🇲'},
    {'code': 'SD', 'name': 'Sudan', 'flag': '🇸🇩'},
    {'code': 'SR', 'name': 'Suriname', 'flag': '🇸🇷'},
    {'code': 'SJ', 'name': 'Svalbarn and Jan Mayen Islands', 'flag': '🇸🇯'},
    {'code': 'SZ', 'name': 'Swaziland', 'flag': '🇸🇿'},
    {'code': 'SE', 'name': 'Sweden', 'flag': '🇸🇪'},
    {'code': 'CH', 'name': 'Switzerland', 'flag': '🇨🇭'},
    {'code': 'SY', 'name': 'Syrian Arab Republic', 'flag': '🇸🇾'},
    {'code': 'TW', 'name': 'Taiwan', 'flag': '🇹🇼'},
    {'code': 'TJ', 'name': 'Tajikistan', 'flag': '🇹🇯'},
    {'code': 'TZ', 'name': 'Tanzania, United Republic of', 'flag': '🇹🇿'},
    {'code': 'TH', 'name': 'Thailand', 'flag': '🇹🇭'},
    {'code': 'TG', 'name': 'Togo', 'flag': '🇹🇬'},
    {'code': 'TK', 'name': 'Tokelau', 'flag': '🇹🇰'},
    {'code': 'TO', 'name': 'Tonga', 'flag': '🇹🇴'},
    {'code': 'TT', 'name': 'Trinidad and Tobago', 'flag': '🇹🇹'},
    {'code': 'TN', 'name': 'Tunisia', 'flag': '🇹🇳'},
    {'code': 'TR', 'name': 'Turkey', 'flag': '🇹🇷'},
    {'code': 'TM', 'name': 'Turkmenistan', 'flag': '🇹🇲'},
    {'code': 'TC', 'name': 'Turks and Caicos Islands', 'flag': '🇹🇨'},
    {'code': 'TV', 'name': 'Tuvalu', 'flag': '🇹🇻'},
    {'code': 'UG', 'name': 'Uganda', 'flag': '🇺🇬'},
    {'code': 'UA', 'name': 'Ukraine', 'flag': '🇺🇦'},
    {'code': 'AE', 'name': 'United Arab Emirates', 'flag': '🇦🇪'},
    {'code': 'GB', 'name': 'United Kingdom', 'flag': '🇬🇧'},
    {'code': 'UM', 'name': 'United States minor outlying islands', 'flag': '🇺🇲'},
    {'code': 'UY', 'name': 'Uruguay', 'flag': '🇺🇾'},
    {'code': 'UZ', 'name': 'Uzbekistan', 'flag': '🇺🇿'},
    {'code': 'VU', 'name': 'Vanuatu', 'flag': '🇻🇺'},
    {'code': 'VA', 'name': 'Vatican City State', 'flag': '🇻🇦'},
    {'code': 'VE', 'name': 'Venezuela', 'flag': '🇻🇪'},
    {'code': 'VN', 'name': 'Vietnam', 'flag': '🇻🇳'},
    {'code': 'VG', 'name': 'Virgin Islands (British)', 'flag': '🇻🇬'},
    {'code': 'VI', 'name': 'Virgin Islands (U.S.)', 'flag': '🇻🇮'},
    {'code': 'WF', 'name': 'Wallis and Futuna Islands', 'flag': '🇼🇫'},
    {'code': 'EH', 'name': 'Western Sahara', 'flag': '🇪🇭'},
    {'code': 'YE', 'name': 'Yemen', 'flag': '🇾🇪'},
    {'code': 'YU', 'name': 'Yugoslavia', 'flag': '🇾🇪'},
    {'code': 'ZR', 'name': 'Zaire', 'flag': '🇨🇩'},
    {'code': 'ZM', 'name': 'Zambia', 'flag': '🇿🇲'},
    {'code': 'ZW', 'name': 'Zimbabwe', 'flag': '🇿🇼'}
];

export default {

    getCountryName (code) {
        let country = countries.find(c => c.code === code);
        if (country) {
            return country.name;
        }
        return code;
    },

    getCountryFlag (code) {
        let country = countries.find(c => c.code === code);
        if (country) {
            return country.flag;
        }
        return code;
    }
}
