export const plans = [
    {
        name: "10K",
        priceMonthly: 9,
        priceYearly: 90,
        stripeIdMonthly: "price_1MYcybBzYJfGgKHPpnXdv8Oe",
        stripeIdYearly: "price_1MYcybBzYJfGgKHP242RJk86",
    },
    {
        name: "100K",
        priceMonthly: 19,
        priceYearly: 190,
        stripeIdMonthly: "price_1MYcyzBzYJfGgKHPuyy0SwuK",
        stripeIdYearly: "price_1MYcyzBzYJfGgKHPuNNhacvF",
    },
    {
        name: "200K",
        priceMonthly: 29,
        priceYearly: 290,
        stripeIdMonthly: "price_1MYczJBzYJfGgKHPS9oWphhC",
        stripeIdYearly: "price_1MYczJBzYJfGgKHPvAznDT9N",
    },
    {
        name: "500K",
        priceMonthly: 49,
        priceYearly: 490,
        stripeIdMonthly: "price_1MYczcBzYJfGgKHPmsMKo8EQ",
        stripeIdYearly: "price_1MYczcBzYJfGgKHPSYImHnYI",
    },
    {
        name: "1M",
        priceMonthly: 89,
        priceYearly: 890,
        stripeIdMonthly: "price_1MYczyBzYJfGgKHPXl4XbDbY",
        stripeIdYearly: "price_1MYczyBzYJfGgKHPdYFTXFzi",
    },
    {
        name: "3M",
        priceMonthly: 119,
        priceYearly: 1190,
        stripeIdMonthly: "price_1MYd0JBzYJfGgKHPA3LJ69WR",
        stripeIdYearly: "price_1MYd0KBzYJfGgKHP0mfQoiwp",
    },
    {
        name: "5M",
        priceMonthly: 149,
        priceYearly: 1490,
        stripeIdMonthly: "price_1MYd0gBzYJfGgKHP2PzPptcg",
        stripeIdYearly: "price_1MYd0gBzYJfGgKHPSK8F6Pe5",
    },
    {
        name: "10M",
        priceMonthly: 199,
        priceYearly: 1990,
        stripeIdMonthly: "price_1MYd0xBzYJfGgKHPg5wmD2Cf",
        stripeIdYearly: "price_1MYd0xBzYJfGgKHPOxb88KJf",
    },
    {
        name: "20M",
        priceMonthly: 349,
        priceYearly: 3490,
        stripeIdMonthly: "price_1MYd1LBzYJfGgKHP5dhjWsJn",
        stripeIdYearly: "price_1MYd1LBzYJfGgKHPn40jSUOD",
    },
    {
        name: "50M",
        priceMonthly: 699,
        priceYearly: 6990,
        stripeIdMonthly: "price_1MYd1kBzYJfGgKHPWBr0v36u",
        stripeIdYearly: "price_1MYd1kBzYJfGgKHPdTcT8HNW",
    },
    {
        name: "100M",
        priceMonthly: 999,
        priceYearly: 9990,
        stripeIdMonthly: "price_1MYd2EBzYJfGgKHPhXP6dQiP",
        stripeIdYearly: "price_1MYd2EBzYJfGgKHPLlBKe63m",
    },
];
