export const plans = [
    {
        name: "10K",
        priceMonthly: 9,
        priceYearly: 90,
        stripeIdMonthly: "price_1MXS75BzYJfGgKHP9QvzENNT",
        stripeIdYearly: "price_1MXS75BzYJfGgKHPH1PoGv8Z",
    },
    {
        name: "100K",
        priceMonthly: 19,
        priceYearly: 190,
        stripeIdMonthly: "price_1MXS7UBzYJfGgKHPveC6vuok",
        stripeIdYearly: "price_1MXS7UBzYJfGgKHP3i7zBJx7",
    },
    {
        name: "200K",
        priceMonthly: 29,
        priceYearly: 290,
        stripeIdMonthly: "price_1MXS7yBzYJfGgKHPoayOABgf",
        stripeIdYearly: "price_1MXS7yBzYJfGgKHPSXhVaWDy",
    },
    {
        name: "500K",
        priceMonthly: 49,
        priceYearly: 490,
        stripeIdMonthly: "price_1MXS8NBzYJfGgKHPn33oziQ6",
        stripeIdYearly: "price_1MXS8NBzYJfGgKHPtNTvFC0v",
    },
    {
        name: "1M",
        priceMonthly: 89,
        priceYearly: 890,
        stripeIdMonthly: "price_1MXS8nBzYJfGgKHPkxexQz3f",
        stripeIdYearly: "price_1MXS8nBzYJfGgKHPI6plfAyg",
    },
    {
        name: "3M",
        priceMonthly: 119,
        priceYearly: 1190,
        stripeIdMonthly: "price_1MXS9CBzYJfGgKHPZlsRE0Dp",
        stripeIdYearly: "price_1MXS9CBzYJfGgKHPgxvCITlX",
    },
    {
        name: "5M",
        priceMonthly: 149,
        priceYearly: 1490,
        stripeIdMonthly: "price_1MXS9jBzYJfGgKHPVsGr5wZA",
        stripeIdYearly: "price_1MXS9jBzYJfGgKHPNDXpQUY5",
    },
    {
        name: "10M",
        priceMonthly: 199,
        priceYearly: 1990,
        stripeIdMonthly: "price_1MXS9zBzYJfGgKHPGxntlHah",
        stripeIdYearly: "price_1MXS9zBzYJfGgKHPcuMa2mqO",
    },
    {
        name: "20M",
        priceMonthly: 349,
        priceYearly: 3490,
        stripeIdMonthly: "price_1MXSAQBzYJfGgKHP2RN2VWdE",
        stripeIdYearly: "price_1MXSAQBzYJfGgKHPO2B7QT7h",
    },
    {
        name: "50M",
        priceMonthly: 699,
        priceYearly: 6990,
        stripeIdMonthly: "price_1MXSAoBzYJfGgKHP9JtyWWjP",
        stripeIdYearly: "price_1MXSAoBzYJfGgKHPufQeLQs1",
    },
    {
        name: "100M",
        priceMonthly: 999,
        priceYearly: 9990,
        stripeIdMonthly: "price_1MXSBEBzYJfGgKHP87xarvL6",
        stripeIdYearly: "price_1MXSBEBzYJfGgKHPXe9tUfzW",
    },
];
